# 7 Сортировка элементов

## 7.1

На вход программе подаётся строка, содержащая список слов разной длины, разделённых пробелом. Число слов не превышает 1000.

Напишите функцию, позволяющую отсортировать данный список по возрастанию длины слов. Если в списке есть слова одинаковой длины, то в результирующем списке необходимо раньше поставить слово, которое стояло раньше в исходном списке. За основу необходимо взять алгоритм сортировки пузырьком.

Программа должна вывести на экран отсортированный список слов через пробел.

In [79]:
def bubble_sort(lst):
    for i in range(0,len(lst)):
        for j in range(0, len(lst)-i-1):
            if len(lst[j]) > len(lst[j+1]):
                lst[j], lst[j+1] = lst[j+1], lst[j]
    return lst


a = list(input().split())
a_sort_by_len = bubble_sort(a)
print(*a_sort_by_len) 

cube circle square rhombus triangle rectangle trapezoid


## 7.2

На вход программе подаётся список целых чисел (из диапазона от -10000 до 10000), разделённых пробелом. Число элементов списка не превышает 10000. Элементы этого списка построчно формируют двумерный квадратный массив numpy. 

Напишите функцию для сортировки элементов массива по следующему правилу: элементы, расположенные в нечётных столбцах (с индексами 1, 3, ...) необходимо отсортировать по невозрастанию, а в чётных столбцах (с индексами 0, 2, ...) - по неубыванию. Сортировка элементов в столбцах массива должна основываться на самописной функции, реализующей алгоритм шейкерной сортировки (усовершенствованной разновидности сортировки пузырьком).

Необходимо вывести на экран в строку через пробел элементы отсортированного по вышеуказанному правилу двумерного массива, взятые построчно.

In [88]:
import numpy as np


def shaker_sort(arr, desc_order=False): 
    start_idx = 0
    end_idx = len(arr) - 1
    is_swapped = True

    while (is_swapped == True): 
        is_swapped = False

        for i in range(start_idx, end_idx): 
            if ((not desc_order and arr[i] > arr[i + 1]) or (desc_order and arr[i] < arr[i + 1])): 
                arr[i], arr[i + 1] = arr[i + 1], arr[i] 
                is_swapped = True

        if (not(is_swapped)): 
            break

        is_swapped = False
        end_idx= end_idx - 1
  
        for i in range(end_idx - 1, start_idx - 1, -1): 
            if ((not desc_order and arr[i] > arr[i + 1]) or (desc_order and arr[i] < arr[i + 1])): 
                arr[i], arr[i + 1] = arr[i + 1], arr[i] 
                is_swapped = True
        start_idx = start_idx + 1


n = list(map(int, input().split()))
size = int(len(n) ** (1/2))
a = np.array(n)
a = a.reshape(size, size)
print(a)
for i in range(size):
    if i % 2 == 0:
        shaker_sort(a.T[i], desc_order=False)
    else:
        shaker_sort(a.T[i], desc_order=True)
print(*a.flatten())

[[ 6173  1085  2240]
 [-8288 -5174  8172]
 [-5855 -4816  3145]]
-8288 1085 2240 -5855 -4816 3145 6173 -5174 8172


In [83]:
n = list(map(int, input().split()))
size = int(len(n) ** (1/2))
a = np.array(n)
a = a.reshape(size, size)
print(a)
print(a.T[0])
a.T[0][0] = -999
print(a)

[[1 9]
 [2 8]]
[1 2]
[[-999    9]
 [   2    8]]


## 7.3

На вход программе подаётся строка, содержащая список слов разной длины, разделённых пробелом. Число слов не превышает 10000. Все слова состоят из букв английского алфавита в нижнем регистре.

Напишите функцию, которая преобразовывает входную строку так, чтобы буквы каждого слова в ней были отсортированы по алфавиту. Порядок самих слов не изменяется. Данная функция должна основываться на самописной функции сортировки подсчётом.

Программа должна вывести на экран список слов через пробел, отсортированных в соответствии с условием задачи.

In [97]:
def count_sort(a, keys_set):
    keys_count = {ch : 0 for ch in keys_set}
    for el in a:
        keys_count[el] += 1
    sorted_a = []
    for key, val in keys_count.items():
        sorted_a += [key] * val
    return sorted_a
        

words = input().split()
result = []
for word in words:
    result.append("".join(count_sort(word, list(map(chr, range(ord('a'), ord('z')+1))))))
print(result)

['aabb', 'aabb', 'abcd', 'abcd']


In [93]:
a = []
a += [2]*0
a

[]

## 7.4 

Даны два отсортированных по невозрастанию целочисленных массива разной длины. Напишите функцию, которая позволит объединить их в один отсортированный по убыванию массив. 

На вход программе подаётся две строки: в первой строке через запятую указаны элементы первого массива, во второй строке через запятую указаны элементы второго массива.

Программа должна вывести на экран через запятую элементы результирующего отсортированного массива, полученного слиянием двух входных массивов.

In [98]:
def merge(lst1, lst2, desc_order=False):
    i = 0 
    j = 0
    lst_res = []
    while i < len(lst1) and j < len(lst2):
        if not desc_order and lst1[i] < lst2[j] \
            or desc_order and lst1[i] > lst2[j]:
            lst_res.append(lst1[i])
            i += 1
        else: 
            lst_res.append(lst2[j])
            j += 1
    while i < len(lst1):
        lst_res.append(lst1[i])
        i += 1
    while j < len(lst2):
        lst_res.append(lst2[j])
        j += 1
    return lst_res
    
            
a1 = list(map(int, input().split(",")))
a2 = list(map(int, input().split(",")))
print(*merge(a1, a2, True), sep=",")

108,90,76,54,37,32,30,10,10,10,5,2,1


## 7.5

Даны два целочисленных списка разной длины. Напишите функцию, которая перераспределит элементы списков так, чтобы в первом списке оказались наименьшие значения среди значений обоих списков (расположенные по возрастанию), а во втором - наибольшие значения среди значений обоих списков (также расположенные по возрастанию). Длины списков не должны изменяться.

На вход программе подаётся две строки: в первой строке через запятую указаны элементы первого списка, во второй строке через запятую указаны элементы второго списка.

Программа должна вывести на экран две строки: в первой строке через запятую элементы результирующего отсортированного списка наименьших элементов, во второй строке - через запятую элементы результирующего отсортированного списка наибольших элементов.

In [105]:
def merge(lst1, lst2, desc_order=False):
    i = 0 
    j = 0
    lst_res = []
    while i < len(lst1) and j < len(lst2):
        if not desc_order and lst1[i] <= lst2[j] \
            or desc_order and lst1[i] >= lst2[j]:
            lst_res.append(lst1[i])
            i += 1
        else: 
            lst_res.append(lst2[j])
            j += 1
    while i < len(lst1):
        lst_res.append(lst1[i])
        i += 1
    while j < len(lst2):
        lst_res.append(lst2[j])
        j += 1
    return lst_res
    
            
a1 = list(map(int, input().split(",")))
a2 = list(map(int, input().split(",")))
res = merge(sorted(a1), sorted(a2))
print(*res[:len(a1)], sep=",")
print(*res[len(a1):], sep=",")

[-9, -6, -6, 1, 2, 4, 9, 33, 49]
[-5, -1, 9, 35, 56, 87]
-9,-6,-6,-5,-1,1,2,4,9
9,33,35,49,56,87
[-9, -6, -6, -5, -1, 1, 2, 4, 9, 9, 33, 35, 49, 56, 87]
