# List and numPy

### 5.1

Эндокринолог Софья Степановна назначает своим пациентам, имеющим заболевания щитовидной железы, через регулярные интервалы времени (через каждые три месяца) сдавать анализ крови для определения уровня тиреотропного гормона (ТТГ), чтобы контролировать эффективность терапии. Она попросила, чтобы в лаборатории результаты анализа каждого пациента заносили в его индивидуальный список. В лаборатории так и поступают и дополнительно делают следующее: если пациент не является на плановую сдачу анализа, то в его список заносится значение -9999.0. 

Напишите программу, на вход которой подаётся список, содержащий результаты анализа ТТГ конкретного пациента через пробел (известно, что пациент хотя бы один раз сдавал анализ). Необходимо удалить из списка все вхождения числа -9999.0 (нужно модифицировать исходный список, не использовать дополнительные новые списки) и вывести точные значения изменённого списка на экран через пробел. Если в списке нет значений -9999.0, то вывести на экран список без изменений.

In [5]:
lst = list(map(float, input().split()))
i = 0
while i != len(lst):
    if lst[i] == -9999.0:
        lst.remove(lst[i])
    else:
        i += 1
print(*['{:.2f}'.format(item) for item in lst])

1.00


### 5.2
Напишите программу, которая принимает на вход список целых чисел, разделённых запятой, и для каждого элемента в списке определяет сумму двух его соседей. Для крайних элементов списка, одним из соседей является элемент, расположенный на другом конце списка. Необходимо вывести на экран соответствующие суммы через точку с запятой.  Если в списке меньше трёх элементов, необходимо вывести на экран исходный список (через точку с запятой).

In [83]:
lst = list(map(int, input().split(",")))
summa = 0
lst_new = []
if len(lst) >= 3:
    for i in range(len(lst)):
        if i < len(lst) - 1:
            summa = lst[i-1] + lst[i+1]
            lst_new.append(summa)
        else:
            summa = lst[0] + lst[-2]
            lst_new.append(summa)
    print(*lst_new, sep=";")
else:
    print(*lst, sep=";")
    
    

3, 7, 11
18;14;10


### 5.3
На вход программе подаётся список натуральных чисел, разделённых пробелом. Необходимо сформировать двумерный квадратный массив numpy,  последовательно располагая элементы списка по строкам массива и вывести на экран через пробел диагональные элементы полученного массива.

In [102]:
import numpy as np


lst = list(map(int, input().split()))
size = int(len(lst) ** (1/2))
a = np.array(lst)
a = a.reshape(size, size)
b = np.diag(a)
print(*b)

2 3 1 5 3 8 7 16 17
2 3 17


### 5.4
Программа принимает на вход четыре натуральных числа N, M, K, S, разделённых пробелом. Необходимо создать целочисленный двумерный массив numpy, содержащий N строк и M столбцов и заполнить его единицами. Затем умножить все чётные строки (0, 2, 4, ...) на K, а все нечётные столбцы (1, 3, 5, ...) умножить на S. Программа должна вывести на экран сумму всех элементов полученного массива.

In [168]:
import numpy as np 


n = list(map(int, input().split()))
a = np.ones((n[0], n[1]))
for row_i in range(0, a.shape[0], 2):
    a[row_i] *= n[2]
for col_i in range(1, a.shape[1], 2):
    a[:,col_i] *= n[3]
print(int(np.sum(a)))

2 3 2 5
21


## 5.5
Сформируйте квадратный двумерный массив numpy, содержащий N строк и N столбцов по следующему правилу: каждый диагональный элемент равен целому числу D, каждый элемент, расположенный над диагональю равен целому числу U, а каждый элемент под диагональю равен целому числу L. Поэлементно сложите все строки и найдите максимальный элемент полученного одномерного массива.

На вход программе подаются четыре строки: N в первой строке, D во второй строке, U в третьей строке, L в четвёртой строке. Ограничения: $$ N\leq1000  , |D|\leq10^8 , |U|\leq10^8  ,  |L|\leq10^8 $$
 

Программа должна вывести на экран значение максимального элемента, полученного по вышеописанному алгоритму.

Sample Input:3 5 -3 2

Sample Output:9

In [10]:
import numpy as np 

n = int(input())
d = int(input())
u = int(input())
l = int(input())
a = np.zeros((n, n), dtype=int)
np.fill_diagonal(a, d)
n_row, n_col = a.shape
for i in range(0, n_row):
    for j in range(0, n_col):
        if i < j:
            a[i][j] = u
        elif i > j:
            a[i][j] = l
print(np.max(np.sum(a, axis=1)))

[[ 5 -3 -3]
 [ 2  5 -3]
 [ 2  2  5]]
9
