# Функции

## 6.1
На вход программе подаётся натуральное число N. Определите, является ли это число совершенным (число совершенно, если оно равно сумме всех своих делителей, кроме самого себя, например, 6 = 1 + 2 + 3). Программа должна вывести на экран yes, если число совершенно, и no в противном случае. Для решения задачи напишите функцию, которая определит совершенность числа.

In [35]:
def perfect_num(n):
    m = 0
    for divider in range(1, n//2 + 1):
        if n % divider == 0:
            m += divider
    if m == n:
        print("yes")
    else:
        print("no")
    return n

n = int(input())
perfect_num(n)

6
yes


6

## 6.2 
Напишите функцию, которая циклически сдвигает целочисленные элементы списка  вправо или влево на указанное число позиций. Сдвиг должен быть кольцевым, то есть те элементы, которые уходят вправо или влево за пределы списка, должны помещаться с другого его конца. Функция должна принимать следующие аргументы: список элементов, количество позиций для сдвига p, p≥0  и переменную, которая укажет, в какую сторону выполнять сдвиг (влево - left или вправо - right). Функция должна вернуть  список, полученный после циклического сдвига.

На вход программе подаётся список целых чисел, записанных в первой строке через пробел; количество позиций для сдвига записано во второй строке и переменная направления сдвига, которая может принимать два значения - left и right, в третьей строке.

Программа должна вывести на экран список значений (через пробел), полученный из функции после циклического сдвига.

In [159]:
def shift(lst, p, way):
    l = len(lst)
    lst_new = []
    if way == "left":
        for i in range(l):
            lst_new.append(lst[(i+p) % l])
    if way == "right":
        for i in range(l):
            lst_new.append(lst[(i-p) % l])
    return lst_new


lst1 = list(map(int, input().split()))
pl = int(input())
direct = input()
print(*shift(lst1, pl, direct))

[4, 5, 1, 8, 3, 9]


In [ ]:
lst1 = [4, 5, 1, 8, 3, 9]
pl = 6
direct = "right"

## 6.3 
Напишите функцию-шифровальщик, которая с помощью специального алгоритма зашифрует заданное предложение. Алгоритм шифрования данных заключается в следующем:

1. Все слова в предложении записываются в обратном порядке.

2. Каждое слово записывается в обратном порядке.

3. Каждая гласная буква удваивается, а каждая согласная - утраивается.

4. Первая и последняя буква каждого слова переводится в верхний регистр (регистр остальных букв остаётся без изменений).

На вход программе подаётся предложение на английском языке (слова разделены пробелом, знаков препинания нет), причём буквы могут быть как в верхнем, так и в нижнем регистре. Необходимо с помощью функции-шифровальщика получить зашифрованное предложение и вывести его на экран. Считается, что буква Y(y) - гласная.

In [236]:
def encryption(lst):
    lst.reverse()
    res = []
    lst = [s[::-1] for s in lst]
    vowels = ["a", "e", "y", "u", "o", "i"]
    for word in lst:
        c_word = ""
        for el in word:
            if el.lower() in vowels:
                c_word += el * 2
            else:
                c_word += el * 3
        c_word = c_word[0].upper() + c_word[1:-1] + c_word[-1].upper()
        res.append(c_word)
        
    return res


lst = list(input().split())
print(*encryption(lst))

EeGGGaasssSSSeemM TTTeeRRRccceesS AA SssI SSSiihhhTT


## 6.4 
Напишите функцию, которая находит произведение квадратной матрицы размером N×N самой на себя, и у матрицы, которая является результатом произведения, определяет минимальный элемент M среди элементов расположенных ниже побочной диагонали.

На вход программе в первой строке подаётся число строк/столбцов квадратной матрицы N, (N≥2). Далее идут N строк, содержащих по N целых чисел (в диапазоне от -100 до 100), записанных через пробел. 

Программа должна вывести на экран результат вызова функции, а именно минимальный элемент M.

In [32]:
import numpy as np 


def find_minimum_from_side_diagonal_of_matrix(a):
    n_row, n_col = a.shape
    min_a = a[-1, -1]
    for i in range(0, n_row):
        for j in range(0, n_col):
            if i + j >= n_row:
                if a[i, j] <= min_a:
                    min_a = a[i, j]
    print(min_a)                
    return min_a

n = int(input())
#lst = []
lst = list(map(int, input().split()))
        # for i in range(n):
        #     nn = list(map(int, input().split()))
        #     lst.append(nn)
if n >= 2:
    a = np.array(lst)
    a = a.reshape(n, n)
    res = np.dot(a, a)
    print(a)
    print(res)
    print(min(find_minimum_from_side_diagonal_of_matrix(a), find_minimum_from_side_diagonal_of_matrix(res)))
else:
    print("Ошибка")

[[  1   6   7  -3  20]
 [ -7 -43   8   3  -6]
 [ 87   1   0   5  -5]
 [  5   3   1 -88   4]
 [ 90  11   6  -4   1]]
[[2353  -34  172  234  -43]
 [ 465 1758 -426 -308   84]
 [-345  439  592 -678 1749]
 [  -9 -318   -5 7727 -271]
 [ 605   72  720  141 1689]]
-88
-678
-678


1 6 7 -3 20 -7 -43 8 3 -6 87 1 0 5 -5 5 3 1 -88 4 90 11 6 -4 1
1 6 7 -3 20 -700 -43 8 3 -6 87 1 0 5 -5 5 3 1 -88 4 90 11 6 -4 1

## 6.5 
На вход программе в первой строке подаётся английское слово S, во второй строке - число N строк/столбцов квадратной матрицы, состоящей из букв английского алфавита, а в третьей строке N^2 
  букв, разделённые пробелом, которые последовательно по строкам формируют квадратную матрицу. Слово и все буквы задаются в нижнем регистре.

Напишите функцию, которая в матрице из букв находит заданное слово S и возвращает позицию (номер строки  i и номер столбца j матрицы в 0-индексации), в которой начинается слово, а так же его расположение LL (вертикально vertically или горизонтально horizontally). Считается, что слово может располагаться непрерывно горизонтально слева-направо или вертикально сверху-вниз. Гарантируется, что заданное слово встречается в матрице не более чем один раз. Длина заданного слова не меньше 2.

Программа должна вывести на экран значения переменных i, j, Li,j,L через запятую. Если заданного слова S нет в матрице, то вывести none. 

In [36]:
import numpy as np


def find_word(a, s):
    for i, row in enumerate(a):
        row_string = "".join(row)
        j = row_string.find(s)
        if j != -1:
            return i, j, "horizontally"
    for j, col in enumerate(a.T):
        col_string = "".join(col)
        i = col_string.find(s)
        if i != -1:
            return i, j, "vertically"

        
s = input()
n = int(input())
lst = input().split()
a = np.array(lst)
a = a.reshape(n, n)
if find_word(a, s):
    print(*find_word(a, s), sep=",")
else:
    print("none")

0,2,vertically
